//! JSON handling — JSON.parse(), JSON.stringify(), and specialized variants
//!
//! Provides all core JSON functions used by compiled TypeScript programs.
//! These live in perry-runtime (not perry-stdlib) so that programs that
//! only use JSON don't need to link the full stdlib.
//!
//! The file was split (issue #1105 wave) into topical sub-modules:
//!
//! - `simd`         — SIMD string-terminator scanners
//! - `parser`       — `DirectParser` recursive-descent implementation
//! - `parse_api`    — `js_json_parse` / `js_json_parse_typed_array` FFI
//! - `stringify`    — core stringify traversal (object/array/scalar emitters)
//! - `stringify_shape_template` — homogeneous-array shape templates
//! - `stringify_api` — `js_json_stringify*` / `js_json_get_*` FFI entries
//! - `replacer`     — replacer + pretty/indent + array-replacer variants
//! - `reviver`      — `JSON.parse(text, reviver)` support
//!
//! Shared TLS state, file-local constants, and tiny helpers used by every
//! sibling stay in this module.

use crate::string::js_string_from_ascii_bytes;
use crate::{js_string_from_bytes, JSValue, StringHeader};
use std::cell::RefCell;

mod parse_api;
mod parser;
// `pub(crate)` so `gc::mod` can register `scan_raw_json_key_root_mut` (#7211):
// the interned `"rawJSON"` key is a GC root.
pub(crate) mod raw_json;
mod replacer;
mod reviver;
mod simd;
mod stringify;
mod stringify_api;
mod stringify_buffer;
mod stringify_scalars;
pub(crate) mod stringify_shape_template;
mod stringify_tojson_probe;

// Public FFI re-exports — preserve the `crate::json::js_json_*` path used by
// the rest of perry-runtime, perry-stdlib, and code generated by perry-codegen.
pub use parse_api::{
    js_json_parse, js_json_parse_or_null, js_json_parse_result, js_json_parse_typed_array,
};
pub use raw_json::{js_json_is_raw_json, js_json_raw_json};
pub use replacer::{js_json_stringify_full, js_json_stringify_with_replacer};
pub use reviver::js_json_parse_with_reviver;
/// #7448: exported so the cross-host UI crates can ASK the runtime whether an
/// address is GC-tracked instead of each carrying its own bit-pattern guess.
/// `perry-ui-android`'s copy tested for a positive IEEE-754 subnormal, which
/// classifies every denormal `Number` as an untagged heap pointer — the exact
/// predicate #7447 removed here after it SIGSEGV'd on `JSON.stringify(1e-317)`.
/// No bit test can decide this: a raw pointer and a positive subnormal occupy
/// the same bit patterns by construction, so the answer has to come from
/// allocation membership, which only the runtime can answer.
pub use stringify::ptr_is_tracked_heap_object;
pub use stringify_api::{
    js_json_get_bool, js_json_get_number, js_json_get_string, js_json_is_valid, js_json_stringify,
    js_json_stringify_bool, js_json_stringify_null, js_json_stringify_number,
    js_json_stringify_string,
};

// Crate-internal symbol surface — siblings reach these via `use super::*;`
// so every cross-sibling helper must be visible at the mod-root scope.
// `ShapeTemplate` is referenced by the `SHAPE_CACHE` thread-local declared
// below so the re-export must precede the `thread_local!` block.
#[cfg(test)]
pub(crate) use parse_api::test_json_parse_direct;
pub(crate) use parser::{DirectParser, ObjectShapeHint};
pub(crate) use raw_json::{ptr_is_raw_json_wrapper, raw_json_text_bytes};
#[cfg(test)]
pub(crate) use reviver::test_apply_reviver_for_value;
pub(crate) use simd::find_string_terminator;
pub(crate) use stringify::{
    arm_to_json_result_guard, check_stringify_nesting_depth, estimate_json_size, is_closure_value,
    is_object_pointer, is_symbol_value, object_get_to_json, stringify_value, write_escaped_string,
    write_number,
};
pub(crate) use stringify_api::{redirect_lazy_to_materialized, try_stringify_lazy_array};
pub(crate) use stringify_buffer::{
    stringify_buffer, stringify_buffer_pretty, stringify_typed_array, stringify_typed_array_pretty,
};
pub(crate) use stringify_shape_template::ShapeTemplate;
pub(crate) use stringify_tojson_probe::{
    current_to_json_key_arg, invalidate_object_proto_tojson_state, reset_to_json_key,
    set_to_json_key_index, set_to_json_key_str, set_to_json_key_value, to_json_definitely_absent,
};

// ─── Circular reference detection ────────────────────────────────────────────
thread_local! {
    /// Stack of object pointers currently being stringified (for circular detection).
    pub(crate) static STRINGIFY_STACK: RefCell<Vec<usize>> = const { RefCell::new(Vec::new()) };

    /// Reusable scratch buffer for JSON.stringify (issue #64). Avoids the
    /// per-call `String::with_capacity` allocate+free that dominated the
    /// small-stringify path. Wrapped in `Cell<Option<_>>` so reentrant calls
    /// (via `toJSON` callbacks etc.) get a fresh buffer instead of panicking
    /// on a `RefCell` borrow conflict; the larger of the two is restored.
    pub(crate) static STRINGIFY_BUF: std::cell::Cell<Option<String>> =
        std::cell::Cell::new(Some(String::with_capacity(4096)));

    /// Per-call shape-template cache (#64 follow-up), as a STACK of frames.
    /// Each template is keyed on its `keys_array` raw pointer, which is a
    /// **GC-managed `ArrayHeader*`** — so `scan_parse_roots_mut` visits every
    /// frame's every key as a real (marking AND rewriting) root.
    ///
    /// ★ #7268: this comment used to assert the invariant that made the raw
    /// key safe —
    ///
    /// > within one top-level stringify call no GC runs over the user object
    /// > graph (the buffer/result allocations don't move keys arrays), so
    /// > pointer identity is a stable shape ID
    ///
    /// — and `toJSON` falsifies it. A `toJSON` is user JS: it allocates, it
    /// can reach a safepoint, and the minor there is evacuating. A stale key
    /// then either misses (merely slow) or, worse, **collides with a
    /// newly-allocated array at the recycled address and matches the wrong
    /// shape**; and `set_to_json_key_for_template_field` reads the property
    /// NAME strings out of `keys_arr`, i.e. dereferences retired from-space.
    ///
    /// ★ Why a stack rather than a moved-out `Vec`. Reentrancy used to be
    /// handled by `take_shape_cache()` moving the whole cache into a Rust
    /// local for the duration of the inner call. While it sat there the root
    /// scanner could not see it, so the inner call — the `toJSON`, i.e.
    /// precisely the code that moves things — left every saved key stale, and
    /// the outer call resumed using them. Keeping the frames in the TLS is
    /// what makes the scanner's coverage complete; `take`/`restore` now push
    /// and pop a frame instead of moving the storage out of the collector's
    /// reach.
    ///
    /// Frame 0 always exists (the top-level call's), so the emit path never
    /// has to check for an empty stack.
    ///
    /// `Box<ShapeTemplate>` lives on the heap so its address is stable
    /// even when a frame `Vec` reallocates — we hand out raw pointers
    /// to the templates and they must outlive the borrow.
    pub(crate) static SHAPE_CACHE: RefCell<Vec<Vec<Box<ShapeTemplate>>>> =
        RefCell::new(vec![Vec::new()]);

    /// Key string intern cache for JSON.parse (issue #51 follow-up).
    /// Maps key bytes → already-allocated StringHeader pointer.
    /// Avoids re-allocating "id", "name", etc. for every record in a
    /// homogeneous JSON array. Cleared at the end of each top-level parse.
    /// `pub(crate)` so `json_tape`'s materializer can share the cache —
    /// without this, each tape-path force-materialize re-allocates every
    /// key and burns 3× the time + RSS vs the direct parser.
    pub(crate) static PARSE_KEY_CACHE: RefCell<std::collections::HashMap<Vec<u8>, *const StringHeader>> =
        RefCell::new(std::collections::HashMap::new());
    /// Tiny hot-key mirror for homogeneous object parses. Most API JSON
    /// repeats the same handful of property names thousands of times; a
    /// short linear probe avoids hashing + HashMap probing on the steady
    /// state while PARSE_KEY_CACHE remains the owning/rooting store.
    static PARSE_KEY_RING: RefCell<Vec<*const StringHeader>> = const { RefCell::new(Vec::new()) };

    /// Shared keys_array cache for direct JSON.parse objects.
    ///
    /// The generic object setter builds a shape one property at a time. For
    /// homogeneous JSON records that means every parsed object participates in
    /// the transition-cache machinery before field values are written. The tape
    /// path avoids that churn by materializing from a compact token stream; the
    /// direct parser needs the same shape sharing so `PERRY_JSON_TAPE=0` does
    /// not manufacture short-lived keys arrays and forwarding stubs in old
    /// pages.
    pub(crate) static PARSE_SHAPE_CACHE: RefCell<Vec<ParseShapeCacheEntry>> =
        const { RefCell::new(Vec::new()) };

    /// Reentrancy depth counter for JSON.stringify (issue #67). 0 means
    /// no call in progress; ≥1 means a reentrant (toJSON callback) path.
    /// Used to skip the shape_cache save/restore dance for the common
    /// non-reentrant case — a plain `clear_shape_cache` at the outermost
    /// call's exit handles correctness without a Vec alloc/swap.
    pub(crate) static STRINGIFY_DEPTH: std::cell::Cell<u32> = const { std::cell::Cell::new(0) };

    /// One-shot guard so `toJSON` is applied at most once per value (#321 /
    /// ECMA-262 §25.5.2.2). `SerializeJSONProperty` calls `value.toJSON(key)`
    /// once and then serializes the RESULT as an ordinary object/array —
    /// without re-invoking `toJSON` on that result. Without this, a `toJSON`
    /// that returns another object whose prototype/own chain also has a
    /// `toJSON` (e.g. `{ toJSON() { return new ClassWithToJSON(); } }`) would
    /// re-apply the inner `toJSON` and diverge from Node. We set this flag
    /// right before serializing an OBJECT-typed `toJSON` result; the very next
    /// `object_get_to_json` consumes (clears) it and returns `None`, so the
    /// result object emits its own fields while its children recurse normally.
    pub(crate) static SUPPRESS_NEXT_TO_JSON: std::cell::Cell<bool> =
        const { std::cell::Cell::new(false) };

    /// The property key handed to `toJSON` for the value currently being
    /// serialized (#5909 — test262 JSON/stringify/value-tojson-arguments).
    /// ECMA-262 §25.5.2.2 SerializeJSONProperty step 2.b.i is
    /// `Call(toJSON, value, « key »)`, where `key` is the empty String at the
    /// root, an object's own property name for a member, and the stringified
    /// index for an array element. Set right before recursing into each child
    /// and read by `object_get_to_json` / `array_get_to_json` /
    /// `bigint_apply_to_json`. Held as an owned Rust `String` (not a JS heap
    /// pointer) so it never roots a movable GC allocation across the string
    /// allocation the probes perform, and reset at every top-level stringify
    /// entry so a key from one call can't leak into the next.
    pub(crate) static TO_JSON_KEY: std::cell::RefCell<String> =
        const { std::cell::RefCell::new(String::new()) };

    /// Cached verdict on whether the default `Object.prototype` carries a
    /// `toJSON` property (#6009). One of `PROTO_TOJSON_DIRTY` /
    /// `PROTO_TOJSON_ABSENT` / `PROTO_TOJSON_PRESENT`. Computed lazily by the
    /// first `object_get_to_json` fast-path probe of a stringify call and
    /// invalidated at every top-level stringify entry and after every user
    /// callback (`toJSON` / replacer) — the only points where user code could
    /// have added `Object.prototype.toJSON` since the last computation.
    pub(crate) static OBJECT_PROTO_TOJSON_STATE: std::cell::Cell<u8> =
        const { std::cell::Cell::new(0) };

    /// One-time-resolved NaN-box bits of the default `Object.prototype`
    /// object (0 = not yet resolved). Resolving it live per stringify call
    /// (`default_object_prototype_bits`: globalThis generic getter + key
    /// alloc + closure prop lookup) dominated the post-#6009 fast-path
    /// profile. Per spec the `Object.prototype` property is non-writable /
    /// non-configurable, so the resolution itself can never change — only
    /// the OBJECT can move under an evacuating GC, which is why this slot is
    /// registered as a GC mutable root
    /// (`scan_json_object_proto_cache_root_mut`): marking visits it and
    /// evacuation rewrites it.
    pub(crate) static CACHED_OBJECT_PROTO_BITS: std::cell::Cell<u64> =
        const { std::cell::Cell::new(0) };

    /// GC roots for in-progress JSON.parse. Each entry is a JSValue bit pattern
    /// (stored as f64 so the scanner can hand it to the NaN-boxed mark path).
    ///
    /// Why this exists (issue #46): parse_array/parse_object build their result
    /// incrementally over thousands of iterations. Mid-parse heap allocations
    /// (`js_string_from_bytes` → gc_malloc → adaptive count trigger, or an arena
    /// block overflow) run GC while the in-progress array/object lives only on
    /// the Rust call stack. The conservative stack scan only captures callee-
    /// saved registers via setjmp; values held in caller-saved regs (or on
    /// the Rust-heap backing of `Vec<(Vec<u8>, JSValue)>` inside parse_object)
    /// are invisible and get swept. Symptom was `JSON.parse(big_array)` silently
    /// truncating at ~1666 records (= when the second adaptive malloc GC fires).
    pub(crate) static PARSE_ROOTS: RefCell<Vec<f64>> = const { RefCell::new(Vec::new()) };
}

pub(crate) struct ParseShapeCacheEntry {
    pub(crate) keys: Vec<*const StringHeader>,
    pub(crate) keys_array: *mut crate::ArrayHeader,
}

pub(crate) const PARSE_SHAPE_CACHE_CAP: usize = 256;

// ─── Shared file-local NaN-box tag / type-hint constants ─────────────────────

pub(crate) const TAG_UNDEFINED: u64 = 0x7FFC_0000_0000_0001;
pub(crate) const TAG_NULL: u64 = 0x7FFC_0000_0000_0002;
pub(crate) const TAG_FALSE: u64 = 0x7FFC_0000_0000_0003;
pub(crate) const TAG_TRUE: u64 = 0x7FFC_0000_0000_0004;
pub(crate) const POINTER_TAG: u64 = 0x7FFD_0000_0000_0000;
pub(crate) const STRING_TAG: u64 = 0x7FFF_0000_0000_0000;
pub(crate) const BIGINT_TAG: u64 = 0x7FFA_0000_0000_0000;
pub(crate) const INT32_TAG: u64 = 0x7FFE_0000_0000_0000;
pub(crate) const POINTER_MASK: u64 = 0x0000_FFFF_FFFF_FFFF;
pub(crate) const INT32_MASK: u64 = 0x0000_0000_FFFF_FFFF;

pub(crate) const TYPE_UNKNOWN: u32 = 0;
pub(crate) const TYPE_OBJECT: u32 = 1;
pub(crate) const TYPE_ARRAY: u32 = 2;

/// Maximum cache entries per call. Workloads with more distinct shapes
/// fall back to per-object building. We never evict — the raw pointers we
/// hand out must outlive cache mutations, and `swap_remove` would drop a
/// `Box` whose heap address might be in active use up the call stack.
/// 32 entries × ~40 bytes ≈ 1.3 KB; a stringify graph that exceeds this
/// gets the pre-cache slow path on overflow shapes only.
pub(crate) const SHAPE_CACHE_CAP: usize = 32;

/// Stringify depth counter — avoids TLS `STRINGIFY_STACK` access for
/// shallow (non-circular) object graphs. Only activates full tracking
/// at depth > MAX_FAST_DEPTH to catch genuine circular refs.
pub(crate) const MAX_FAST_DEPTH: u32 = 128;

// ─── Parse-roots helpers ─────────────────────────────────────────────────────

#[inline]
pub(crate) fn parse_root_push(v: JSValue) -> usize {
    PARSE_ROOTS.with(|r| {
        let mut r = r.borrow_mut();
        let idx = r.len();
        r.push(f64::from_bits(v.bits()));
        idx
    })
}

#[inline]
pub(crate) fn parse_root_set(idx: usize, v: JSValue) {
    PARSE_ROOTS.with(|r| {
        if let Some(slot) = r.borrow_mut().get_mut(idx) {
            *slot = f64::from_bits(v.bits());
        }
    });
}

#[inline]
pub(crate) fn parse_root_get(idx: usize) -> JSValue {
    PARSE_ROOTS.with(|r| {
        r.borrow()
            .get(idx)
            .map(|slot| JSValue::from_bits(slot.to_bits()))
            .unwrap_or_else(JSValue::undefined)
    })
}

#[inline]
pub(crate) fn parse_root_object_ptr(idx: usize) -> *mut crate::ObjectHeader {
    (parse_root_get(idx).bits() & POINTER_MASK) as *mut crate::ObjectHeader
}

#[inline]
pub(crate) fn parse_root_array_ptr(idx: usize) -> *mut crate::ArrayHeader {
    (parse_root_get(idx).bits() & POINTER_MASK) as *mut crate::ArrayHeader
}

#[inline]
pub(crate) fn parse_root_save_len() -> usize {
    PARSE_ROOTS.with(|r| r.borrow().len())
}

#[inline]
pub(crate) fn parse_root_restore(len: usize) {
    PARSE_ROOTS.with(|r| r.borrow_mut().truncate(len));
}

#[inline]
pub(crate) fn cached_parse_key_ptr(key_bytes: &[u8]) -> *const StringHeader {
    let ring_hit = PARSE_KEY_RING.with(|ring| {
        for &ptr in ring.borrow().iter() {
            if ptr.is_null() {
                continue;
            }
            unsafe {
                let len = (*ptr).byte_len as usize;
                if len != key_bytes.len() {
                    continue;
                }
                let data = (ptr as *const u8).add(std::mem::size_of::<StringHeader>());
                if std::slice::from_raw_parts(data, len) == key_bytes {
                    return Some(ptr);
                }
            }
        }
        None
    });
    if let Some(ptr) = ring_hit {
        return ptr;
    }

    let cached = PARSE_KEY_CACHE.with(|c| c.borrow().get(key_bytes).copied());
    if let Some(ptr) = cached {
        remember_parse_key_ring(ptr);
        return ptr;
    }

    // Issue #179: allocate cached key strings in the longlived arena. They
    // are rooted by `scan_parse_roots_mut` and reused across repeated parses
    // of homogeneous JSON records.
    let ptr =
        crate::string::js_string_from_bytes_longlived(key_bytes.as_ptr(), key_bytes.len() as u32);
    PARSE_KEY_CACHE.with(|c| {
        c.borrow_mut().insert(key_bytes.to_vec(), ptr);
    });
    remember_parse_key_ring(ptr);
    ptr
}

#[inline]
fn remember_parse_key_ring(ptr: *const StringHeader) {
    PARSE_KEY_RING.with(|ring| {
        let mut ring = ring.borrow_mut();
        if ring.contains(&ptr) {
            return;
        }
        if ring.len() == 16 {
            ring.remove(0);
        }
        ring.push(ptr);
    });
}

pub(crate) fn clear_parse_key_ring() {
    PARSE_KEY_RING.with(|ring| ring.borrow_mut().clear());
}

#[inline]
pub(crate) unsafe fn parse_shape_keys_array(
    keys: &[*const StringHeader],
) -> *mut crate::ArrayHeader {
    PARSE_SHAPE_CACHE.with(|cache| {
        {
            let cache = cache.borrow();
            for entry in cache.iter().rev() {
                if entry.keys.len() == keys.len()
                    && entry
                        .keys
                        .iter()
                        .zip(keys.iter())
                        .all(|(a, b)| std::ptr::eq(*a, *b))
                {
                    return entry.keys_array;
                }
            }
        }

        let arr = crate::array::js_array_alloc_with_length_longlived(keys.len() as u32);
        let elements_ptr =
            (arr as *mut u8).add(std::mem::size_of::<crate::ArrayHeader>()) as *mut f64;
        for (i, &key_ptr) in keys.iter().enumerate() {
            let bits = crate::value::STRING_TAG | (key_ptr as u64 & crate::value::POINTER_MASK);
            // GC_STORE_AUDIT(INIT): parse shape keys array is filled before cache publication.
            *elements_ptr.add(i) = f64::from_bits(bits);
            crate::array::note_array_slot_layout_only(arr, i, bits);
        }
        let header = (arr as *mut u8).sub(crate::gc::GC_HEADER_SIZE) as *mut crate::gc::GcHeader;
        (*header).gc_flags |= crate::gc::GC_FLAG_SHAPE_SHARED;

        let mut cache = cache.borrow_mut();
        if cache.len() < PARSE_SHAPE_CACHE_CAP {
            cache.push(ParseShapeCacheEntry {
                keys: keys.to_vec(),
                keys_array: arr,
            });
        }
        arr
    })
}

// ─── Stringify scratch / shape-cache lifecycle ───────────────────────────────

/// Take the shared scratch buffer (or allocate a fresh one on reentrancy).
#[inline]
pub(crate) fn take_stringify_buf() -> String {
    STRINGIFY_BUF.with(|b| b.take()).unwrap_or_default()
}

/// Restore the scratch buffer after use. In a reentrant call the inner
/// restore runs first with a (typically smaller) buffer, but the outer
/// restore runs last and overwrites with its larger buffer — so the
/// final TLS state always holds the largest recently-used buffer without
/// needing a per-call capacity comparison.
#[inline]
pub(crate) fn restore_stringify_buf(mut buf: String) {
    buf.clear();
    STRINGIFY_BUF.with(|b| b.set(Some(buf)));
}

#[inline]
pub(crate) fn json_string_from_output_bytes(bytes: &[u8]) -> *mut StringHeader {
    if bytes.is_ascii() {
        js_string_from_ascii_bytes(bytes.as_ptr(), bytes.len() as u32)
    } else {
        js_string_from_bytes(bytes.as_ptr(), bytes.len() as u32)
    }
}

/// Receipt for a pushed shape-cache frame. Consumed by `restore_shape_cache`.
///
/// It is not `Copy` and carries a `Drop` that pops the frame, so a JS exception
/// unwinding past the matching `restore_shape_cache` cannot leave the stack one
/// frame deep forever. (`clear_shape_cache` truncates to frame 0 as a second
/// line of defence, for the `longjmp`-style exits that skip `Drop` entirely.)
pub(crate) struct SavedShapeCache {
    restored: bool,
}

impl Drop for SavedShapeCache {
    fn drop(&mut self) {
        if !self.restored {
            SHAPE_CACHE.with(|c| {
                let mut stack = c.borrow_mut();
                if stack.len() > 1 {
                    stack.pop();
                }
            });
        }
    }
}

/// Push a fresh shape-cache frame for the duration of a nested stringify call.
/// A reentrant `toJSON` callback would otherwise inherit the outer call's
/// templates and (worse) clear them on exit, dangling pointers we already
/// handed out. Mirrors `take_stringify_buf` in spirit.
///
/// #7268: this used to `mem::take` the cache into a Rust local. The storage
/// then sat outside the TLS — and therefore outside `scan_parse_roots_mut`'s
/// reach — for the whole of the inner call, which is the call that runs user
/// `toJSON` code and moves things. Pushing a frame keeps every saved key
/// visible to the collector.
#[inline]
pub(crate) fn take_shape_cache() -> SavedShapeCache {
    SHAPE_CACHE.with(|c| c.borrow_mut().push(Vec::new()));
    SavedShapeCache { restored: false }
}

#[inline]
pub(crate) fn restore_shape_cache(mut saved: SavedShapeCache) {
    saved.restored = true;
    SHAPE_CACHE.with(|c| {
        let mut stack = c.borrow_mut();
        if stack.len() > 1 {
            stack.pop();
        }
    });
}

/// Clear the cache without allocating a fresh Vec (keeps capacity, drops
/// entries). Used in place of restore when we know the cache was empty at call
/// entry — the outermost stringify call in a tight loop skips the save
/// entirely.
///
/// It also truncates the frame stack back to one, which is what re-establishes
/// the invariant after a JS exception unwound past a `restore_shape_cache`.
#[inline]
pub(crate) fn clear_shape_cache() {
    SHAPE_CACHE.with(|c| {
        let mut stack = c.borrow_mut();
        stack.truncate(1);
        stack[0].clear();
    });
}

/// The live shape-cache frame — the innermost stringify call's.
#[inline]
pub(crate) fn with_shape_cache_frame<R>(f: impl FnOnce(&mut Vec<Box<ShapeTemplate>>) -> R) -> R {
    SHAPE_CACHE.with(|c| {
        let mut stack = c.borrow_mut();
        let frame = stack.last_mut().expect("shape cache always has frame 0");
        f(frame)
    })
}

#[inline]
pub(crate) fn make_pointer_bits(ptr: *const u8) -> u64 {
    POINTER_TAG | (ptr as u64 & POINTER_MASK)
}

// ─── GC root scanners ────────────────────────────────────────────────────────

/// Root scanner called by GC — marks every value in PARSE_ROOTS as live.
pub fn scan_parse_roots(mark: &mut dyn FnMut(f64)) {
    let mut visitor = crate::gc::RuntimeRootVisitor::for_copy(mark);
    scan_parse_roots_mut(&mut visitor);
}

pub fn scan_parse_roots_mut(visitor: &mut crate::gc::RuntimeRootVisitor<'_>) {
    PARSE_ROOTS.with(|r| {
        for v in r.borrow_mut().iter_mut() {
            visitor.visit_nanbox_f64_slot(v);
        }
    });
    // Also mark interned key strings so GC doesn't sweep them mid-parse.
    PARSE_KEY_CACHE.with(|c| {
        for ptr in c.borrow_mut().values_mut() {
            visitor.visit_tagged_raw_const_ptr_slot(ptr, crate::value::STRING_TAG);
        }
    });
    // PARSE_KEY_RING mirrors the cache's hottest values. It does not own
    // their liveness, but its duplicate addresses must follow an old-page
    // move after PARSE_KEY_CACHE has kept the strings alive.
    PARSE_KEY_RING.with(|ring| {
        for ptr in ring.borrow_mut().iter_mut() {
            let mut addr = *ptr as usize;
            if visitor.visit_metadata_usize_slot(&mut addr) {
                *ptr = addr as *const StringHeader;
            }
        }
    });
    PARSE_SHAPE_CACHE.with(|c| {
        for entry in c.borrow_mut().iter_mut() {
            visitor.visit_raw_mut_ptr_slot(&mut entry.keys_array);
            for key in entry.keys.iter_mut() {
                visitor.visit_tagged_raw_const_ptr_slot(key, crate::value::STRING_TAG);
            }
        }
    });
    // #7268: the STRINGIFY-side shape cache keys every template on a raw
    // `ArrayHeader*` and reads the property-name strings back out of it. Its
    // doc comment used to claim no GC could run over the user object graph
    // during one stringify call; `toJSON` is user JS and falsifies that. Marked
    // AND rewritten, on EVERY frame — the reentrancy save is a pushed frame
    // rather than a moved-out `Vec` precisely so that "every frame" is
    // reachable from here (see `SHAPE_CACHE`).
    SHAPE_CACHE.with(|c| {
        for frame in c.borrow_mut().iter_mut() {
            for template in frame.iter_mut() {
                let mut keys_arr = template.keys_arr.get();
                if keys_arr.is_null() {
                    continue;
                }
                visitor.visit_raw_mut_ptr_slot(&mut keys_arr);
                template.keys_arr.set(keys_arr);
            }
        }
    });
    // #6009: the once-resolved default-`Object.prototype` cache must be
    // rewritten when an evacuating GC moves the prototype object (and marked
    // so the slot can never point at swept memory). Guard against a stale
    // pointer whose backing arena block no longer exists (the unit-test
    // harness resets arenas between tests while thread-locals persist):
    // visiting it would walk freed memory, so drop the cache instead — the
    // next stringify probe simply re-resolves.
    CACHED_OBJECT_PROTO_BITS.with(|c| {
        let mut bits = c.get();
        if bits != 0 {
            let addr = (bits & crate::value::POINTER_MASK) as usize;
            if matches!(
                crate::arena::classify_heap_generation(addr),
                crate::arena::HeapGeneration::Unknown
            ) {
                c.set(0);
            } else {
                visitor.visit_nanbox_u64_slot(&mut bits);
                c.set(bits);
            }
        }
    });
}

#[cfg(test)]
pub(crate) fn test_seed_parse_roots(value: f64, key_ptr: *const StringHeader) {
    PARSE_ROOTS.with(|r| {
        let mut r = r.borrow_mut();
        r.clear();
        r.push(value);
    });
    PARSE_KEY_CACHE.with(|c| {
        let mut c = c.borrow_mut();
        c.clear();
        c.insert(b"test".to_vec(), key_ptr);
    });
}

#[cfg(test)]
pub(crate) fn test_seed_parse_key_ring(key_ptr: *const StringHeader) {
    PARSE_KEY_RING.with(|ring| {
        let mut ring = ring.borrow_mut();
        ring.clear();
        ring.push(key_ptr);
    });
}

#[cfg(test)]
pub(crate) fn test_parse_key_ring_snapshot() -> Vec<usize> {
    PARSE_KEY_RING.with(|ring| ring.borrow().iter().map(|&ptr| ptr as usize).collect())
}

/// Seed the stringify-side shape cache with a template keyed on `keys_arr`,
/// so #7268's scanner tests can exercise the mark/rewrite halves without
/// having to drive a whole `JSON.stringify` to populate it.
#[cfg(test)]
pub(crate) fn test_seed_stringify_shape_cache(keys_arr: *mut crate::ArrayHeader) {
    clear_shape_cache();
    with_shape_cache_frame(|frame| {
        frame.push(Box::new(ShapeTemplate {
            keys_arr: std::cell::Cell::new(keys_arr),
            prefixes: vec![String::from("{\"id\":")],
            shape_fields: 1,
            primitive_only: true,
        }));
    });
}

/// Every frame's every `keys_arr`, in order — what the scanner is expected to
/// have rewritten.
#[cfg(test)]
pub(crate) fn test_stringify_shape_cache_keys() -> Vec<usize> {
    SHAPE_CACHE.with(|c| {
        c.borrow()
            .iter()
            .flat_map(|frame| frame.iter().map(|t| t.keys_arr.get() as usize))
            .collect()
    })
}

#[cfg(test)]
pub(crate) fn test_clear_parse_roots() {
    PARSE_ROOTS.with(|r| r.borrow_mut().clear());
    PARSE_KEY_CACHE.with(|c| c.borrow_mut().clear());
    PARSE_KEY_RING.with(|ring| ring.borrow_mut().clear());
    PARSE_SHAPE_CACHE.with(|cache| cache.borrow_mut().clear());
    // #7268: the stringify-side cache is a GC root now, so a template left
    // behind by an earlier test on this thread would hand the next test's
    // collector a pointer into an arena that no longer exists.
    clear_shape_cache();
}

#[cfg(test)]
pub(crate) fn test_parse_roots_snapshot() -> (u64, usize) {
    let value_bits =
        PARSE_ROOTS.with(|r| r.borrow().first().copied().map(f64::to_bits).unwrap_or(0));
    let key_ptr = PARSE_KEY_CACHE.with(|c| {
        c.borrow()
            .get(b"test".as_slice())
            .copied()
            .map(|ptr| ptr as usize)
            .unwrap_or(0)
    });
    (value_bits, key_ptr)
}

// ─── Zero-copy string access + tag/pointer helpers ───────────────────────────

#[inline]
pub(crate) unsafe fn str_from_header<'a>(ptr: *const StringHeader) -> Option<&'a str> {
    if ptr.is_null() || (ptr as usize) < 0x1000 {
        return None;
    }
    let len = (*ptr).byte_len as usize;
    let data_ptr = (ptr as *const u8).add(std::mem::size_of::<StringHeader>());
    let bytes = std::slice::from_raw_parts(data_ptr, len);
    Some(std::str::from_utf8_unchecked(bytes))
}

/// Minimum alignment of a GC allocation's *user* address. Every arena object
/// is `header + GC_HEADER_SIZE` with an 8-aligned header (`arena_alloc_gc`
/// pads `total` to `max(align, 8)`), and `gc_malloc` inherits the system
/// allocator's ≥16-byte alignment, so a misaligned word is never one.
const RAW_POINTER_ALIGN: u64 = 8;

/// True when `bits` carry no NaN-box tag and *could* address a heap object:
/// no tag bits set, non-zero, and [`RAW_POINTER_ALIGN`]-aligned.
///
/// NECESSARY, NEVER SUFFICIENT — this is a cheap pre-filter, not a decision.
/// Call sites must use [`is_raw_pointer`]; see its doc for why.
#[inline]
pub(crate) fn untagged_pointer_bits(bits: u64) -> bool {
    // Every NaN-box tag lives in the top 12 bits (`0x7FF9`..=`0x7FFF`, plus the
    // sign bit for negative NaNs), so an untagged pointer has `bits >> 52 == 0`.
    // `0` is `+0.0`, never a pointer.
    bits >> 52 == 0 && bits != 0 && bits % RAW_POINTER_ALIGN == 0
}

/// True when `bits` — which carry no NaN-box tag — name a heap object that the
/// JSON walk may dereference.
///
/// ## Why the bit pattern alone is not an answer (remote-triggerable SIGSEGV)
///
/// The historical test was `exponent == 0 && mantissa != 0 && sign == 0`, which
/// is bit-for-bit the IEEE-754 definition of a **positive subnormal double**.
/// Every positive denormal reaching `JSON.stringify` was therefore classified
/// as an untagged heap pointer and dereferenced. `JSON.stringify(1e-317)`
/// SIGSEGV'd and `JSON.stringify(5e-324)` printed `null` — both reachable from
/// untrusted input as `JSON.stringify(JSON.parse(text))`.
///
/// No bit-pattern test can fix that, and narrowing the mask is not a fix. A raw
/// untagged pointer and a positive subnormal occupy the *same* bit patterns by
/// construction; that is a property of the value representation, not a wrong
/// constant. `addr_class::is_plausible_heap_addr` does not help either — it is
/// `0x1000..0x8000_0000_0000` on macOS/Linux, while positive subnormals span
/// `0..0x0010_0000_0000_0000`, so the overlap is nearly the whole band. The
/// #3576 module-slot object pointers this branch exists to serve live squarely
/// inside the subnormal range, so any bit test wide enough to admit them still
/// admits denormals.
///
/// The decision therefore has to come from *outside* the bits: ask whether the
/// address is an allocation the GC actually tracks.
/// [`stringify::ptr_is_tracked_heap_object`] answers that from the arena page
/// map and the malloc-object registry — set-membership lookups, no dereference
/// — so a denormal is rejected without ever touching memory and falls through
/// to the `write_number` arm that should have had it all along.
///
/// What remains is exactly the irreducible ambiguity of the representation: a
/// denormal whose bits *equal* a live tracked allocation's address is still
/// indistinguishable from that pointer. Removing that residue means tagging
/// these values at the producer (see `value::equality::normalize_raw_object_bits`
/// / #3576), not writing a better predicate here.
#[inline]
pub(crate) unsafe fn is_raw_pointer(bits: u64) -> bool {
    untagged_pointer_bits(bits) && stringify::ptr_is_tracked_heap_object(bits as *const u8)
}

#[inline]
pub(crate) unsafe fn extract_pointer(bits: u64) -> Option<*const u8> {
    let tag = bits & 0xFFFF_0000_0000_0000;
    if tag == POINTER_TAG {
        Some((bits & POINTER_MASK) as *const u8)
    } else if is_raw_pointer(bits) {
        Some(bits as *const u8)
    } else {
        None
    }
}

/// Read the GC header's object type tag for a user-space heap pointer.
/// The GcHeader sits 8 bytes before `ptr`; its first byte is `obj_type`.
/// Returns 0 when `ptr` is null, in the low-memory guard range, or a value
/// that is not a plausible heap address (a small-handle-band id, e.g. a
/// revocable-Proxy id / fetch / zlib / stream handle, or NaN-box tag remnant).
///
/// The handle-band guard is load-bearing: a `POINTER_TAG`/raw-pointer-shaped
/// field can carry a registry handle id (Next.js render reaches
/// `JSON.stringify(value, replacer)` over an object holding a revocable-Proxy
/// id in the `[0xF0000, 0x100000)` band). Dereferencing `id - 8` as a GcHeader
/// segfaults, so classify by magnitude FIRST. Mirrors the plain-stringify
/// path's `is_closure_value` / `is_handle_band` guards (#4904, #1843) and the
/// canonical `addr_class::try_read_gc_header` contract.
#[inline]
pub(crate) unsafe fn gc_obj_type(ptr: *const u8) -> u8 {
    if ptr.is_null() || (ptr as usize) < 0x1000 {
        return 0;
    }
    match crate::value::addr_class::try_read_gc_header(ptr as usize) {
        Some(header) => header.obj_type,
        None => 0,
    }
}

/// NaN-box a string pointer as f64 (STRING_TAG)
#[inline]
pub(crate) fn nanbox_string_f64(ptr: *const StringHeader) -> f64 {
    f64::from_bits(STRING_TAG | (ptr as u64 & POINTER_MASK))
}

/// NaN-box an object/array pointer as f64 (POINTER_TAG)
#[inline]
// #854: NaN-boxing pointer helper retained for the JSON subsystem (see CLAUDE.md)
#[allow(dead_code)]
pub(crate) fn nanbox_pointer_f64(ptr: *const u8) -> f64 {
    f64::from_bits(POINTER_TAG | (ptr as u64 & POINTER_MASK))
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn direct_parse_shared_shape_preserves_duplicate_key_semantics() {
        let input = br#"{"a":1,"a":2,"b":{"c":3}}"#;
        let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
        let value = unsafe { js_json_parse(text) };
        let obj = (value.bits() & POINTER_MASK) as *const crate::ObjectHeader;
        let key_a = js_string_from_bytes(b"a".as_ptr(), 1);
        let key_b = js_string_from_bytes(b"b".as_ptr(), 1);

        unsafe {
            assert_eq!((*crate::object::object_keys_array(obj)).length, 2);
        }
        let a = crate::object::js_object_get_field_by_name(obj, key_a);
        assert_eq!(f64::from_bits(a.bits()), 2.0);

        let b = crate::object::js_object_get_field_by_name(obj, key_b);
        assert!(b.is_pointer());
        let nested = (b.bits() & POINTER_MASK) as *const crate::ObjectHeader;
        unsafe {
            assert_eq!((*crate::object::object_keys_array(nested)).length, 1);
        }
    }

    /// #7792 / #7817 — deeply nested input must not take the process out.
    ///
    /// Both parsers that read the document recurse once per nesting level, so
    /// a deep enough document exhausted the stack: SIGSEGV, exit 139, no
    /// output at all. The input shape here is a well-known one for untrusted
    /// data, which is why a crash is the wrong answer even though a very deep
    /// document is unusual.
    mod nesting_depth {
        use super::*;
        use crate::json::parser::{
            nesting_depth_exceeds, MAX_ITERATIVE_NESTING_DEPTH, MAX_RECURSIVE_NESTING_DEPTH,
        };

        fn nested_arrays(depth: usize, leaf: u8) -> Vec<u8> {
            let mut input = Vec::with_capacity(depth * 2 + 1);
            input.extend(std::iter::repeat_n(b'[', depth));
            input.push(leaf);
            input.extend(std::iter::repeat_n(b']', depth));
            input
        }

        #[test]
        fn the_scan_counts_only_structural_brackets() {
            assert!(!nesting_depth_exceeds(b"[[[]]]", 8));
            assert!(nesting_depth_exceeds(b"[[[[[[[[[[]]]]]]]]]]", 4));
            assert!(!nesting_depth_exceeds(br#"{"a":{"b":1}}"#, 4));
            assert!(nesting_depth_exceeds(br#"{"a":{"b":1}}"#, 1));

            // Brackets inside a string are text, not structure. Without this a
            // single long string value would be rejected as deep nesting.
            assert!(!nesting_depth_exceeds(br#"{"a":"[[[[[[[[[["}"#, 3));
            // ...including one that ends in an escaped quote, so the scanner
            // does not lose track of where the string closes.
            assert!(!nesting_depth_exceeds(br#"{"a":"[[[\"[[["}"#, 3));

            // The scan runs BEFORE syntax validation, so it sees malformed
            // input. An unbalanced closer must clamp, not underflow.
            assert!(!nesting_depth_exceeds(b"]]]]]]", 2));
            assert!(!nesting_depth_exceeds(b"", 0));
        }

        /// Pin the parser handoff boundary: both sides produce a value.
        #[test]
        fn parse_switches_to_the_iterative_path_past_the_recursive_threshold() {
            let ok_depth = MAX_RECURSIVE_NESTING_DEPTH - 1;
            let ok = nested_arrays(ok_depth, b'0');
            let text = js_string_from_bytes(ok.as_ptr(), ok.len() as u32);
            assert!(
                unsafe { js_json_parse_result(text) }.is_ok(),
                "input below the handoff must parse"
            );

            let deep_depth = MAX_RECURSIVE_NESTING_DEPTH + 1;
            let deep = nested_arrays(deep_depth, b'0');
            let text = js_string_from_bytes(deep.as_ptr(), deep.len() as u32);
            assert!(
                unsafe { js_json_parse_result(text) }.is_ok(),
                "input above the handoff must parse through the heap-stack path"
            );
        }

        #[test]
        fn parses_three_hundred_thousand_levels_on_a_small_worker_stack() {
            const DEPTH: usize = 300_000;
            std::thread::Builder::new()
                .name("json-deep-worker".into())
                .stack_size(2 * 1024 * 1024)
                .spawn(|| {
                    let input = nested_arrays(DEPTH, b'7');
                    let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
                    let mut value = unsafe { js_json_parse_result(text) }
                        .expect("deep JSON must parse on a worker-sized stack");

                    for level in 0..DEPTH {
                        assert!(value.is_pointer(), "level {level} must be an array");
                        let array = (value.bits() & POINTER_MASK) as *const crate::ArrayHeader;
                        assert_eq!(unsafe { (*array).length }, 1, "level {level}");
                        value = crate::array::js_array_get(array, 0);
                    }
                    assert_eq!(f64::from_bits(value.bits()), 7.0);
                })
                .expect("worker thread starts")
                .join()
                .expect("worker parse does not panic");
        }

        #[test]
        fn rejects_nesting_beyond_the_iterative_resource_budget() {
            let input = nested_arrays(MAX_ITERATIVE_NESTING_DEPTH + 1, b'0');
            let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
            let error = unsafe { js_json_parse_result(text) }
                .expect_err("the iterative path must keep a finite resource budget");
            let error = (error.to_bits() & POINTER_MASK) as *const crate::error::ErrorHeader;
            assert_eq!(
                unsafe { (*error).error_kind },
                crate::error::ERROR_KIND_RANGE_ERROR
            );
        }

        #[test]
        fn iterative_path_still_rejects_malformed_json() {
            let depth = MAX_RECURSIVE_NESTING_DEPTH + 1;
            let mut trailing = nested_arrays(depth, b'0');
            trailing.push(b'x');
            let mut invalid_number = Vec::with_capacity(depth * 2 + 2);
            invalid_number.extend(std::iter::repeat_n(b'[', depth));
            invalid_number.extend_from_slice(b"01");
            invalid_number.extend(std::iter::repeat_n(b']', depth));

            for input in [trailing, invalid_number] {
                let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
                assert!(unsafe { js_json_parse_result(text) }.is_err());
            }
        }
    }

    #[test]
    fn parse_result_streaming_validation_rejects_malformed_and_trailing_input() {
        for input in [
            br#"{"a":[1,]}"#.as_slice(),
            br#"{"a":1} trailing"#.as_slice(),
        ] {
            let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
            assert!(
                unsafe { js_json_parse_result(text) }.is_err(),
                "invalid JSON must be rejected before Perry tree construction"
            );
        }

        let valid = br#"{"a":[1,2,3]}"#;
        let text = js_string_from_bytes(valid.as_ptr(), valid.len() as u32);
        assert!(unsafe { js_json_parse_result(text) }.is_ok());
    }

    /// The bare bit test is *exactly* the IEEE-754 positive-subnormal
    /// predicate. Pinning that here so nobody "simplifies"
    /// `untagged_pointer_bits` back into a sufficient condition: whatever it
    /// accepts, it accepts real `Number`s too, which is why `is_raw_pointer`
    /// must consult the GC's allocation set.
    #[test]
    fn untagged_pointer_bits_cannot_separate_pointers_from_subnormals() {
        for v in [5e-324f64, 1e-320, 1e-317, 1e-310, 2.2250738585072009e-308] {
            assert!(v.is_subnormal() && v > 0.0);
            let bits = v.to_bits();
            let old_predicate = (bits >> 52) & 0x7FF == 0 && bits & 0x000F_FFFF_FFFF_FFFF != 0;
            assert!(
                old_predicate,
                "{v:e} is a positive subnormal, so the pre-fix bit test called it a pointer"
            );
        }
        // ...and the bit test still admits the aligned ones. Only the
        // GC-tracking check below rejects them.
        assert!(untagged_pointer_bits(0x0000_0012_3456_7888));
        assert!(!untagged_pointer_bits(0));
        assert!(!untagged_pointer_bits(1.5f64.to_bits()));
        assert!(!untagged_pointer_bits(POINTER_TAG | 0x1000));
    }

    /// A positive subnormal `Number` must serialize as that number. Pre-fix
    /// `5e-324` printed `null` (its bits, `1`, landed in the handle band) and
    /// `1e-317` SIGSEGV'd (its bits pass every magnitude check but address an
    /// unmapped page). Both are reachable from untrusted input via
    /// `JSON.stringify(JSON.parse(text))`.
    #[test]
    fn stringify_positive_subnormal_is_a_number_not_a_pointer() {
        unsafe {
            for (value, expected) in [
                (5e-324f64, "5e-324"),
                (1e-320, "1e-320"),
                (1e-317, "1e-317"),
                (1e-310, "1e-310"),
                (-1e-310, "-1e-310"),
                (2.2250738585072009e-308, "2.225073858507201e-308"),
            ] {
                let output = js_json_stringify(value, TYPE_UNKNOWN);
                assert_eq!(
                    str_from_header(output).unwrap(),
                    expected,
                    "JSON.stringify({value:e})"
                );
            }
        }
    }

    /// Subnormals nested where the object/array field decoders read them —
    /// the `is_raw_pointer` call sites in `stringify.rs` /
    /// `stringify_shape_template.rs`, not just the top-level dispatch.
    #[test]
    fn stringify_subnormal_object_and_array_members() {
        let input = br#"{"n":1e-310,"m":5e-324,"a":[1e-317,1.5],"s":"hi"}"#;
        let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
        let value = unsafe { js_json_parse(text) };
        let output = unsafe { js_json_stringify(f64::from_bits(value.bits()), TYPE_UNKNOWN) };
        assert_eq!(
            unsafe { str_from_header(output) }.unwrap(),
            r#"{"n":1e-310,"m":5e-324,"a":[1e-317,1.5],"s":"hi"}"#
        );
    }

    /// The branch `is_raw_pointer` exists for: an object whose heap pointer
    /// travels UNTAGGED in an f64 slot (#3576 module-level object/array
    /// variables). Rejecting subnormals must not reject these — the fix keys
    /// on GC allocation membership, so a real allocation still resolves.
    #[test]
    fn stringify_untagged_raw_object_pointer_still_serializes() {
        let input = br#"{"a":1,"b":"two"}"#;
        let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
        let value = unsafe { js_json_parse(text) };
        let addr = value.bits() & POINTER_MASK;
        // No tag at all — exactly the shape a module-slot object variable has.
        assert!(
            unsafe { is_raw_pointer(addr) },
            "0x{addr:x} must be admitted"
        );
        let output = unsafe { js_json_stringify(f64::from_bits(addr), TYPE_UNKNOWN) };
        assert_eq!(
            unsafe { str_from_header(output) }.unwrap(),
            r#"{"a":1,"b":"two"}"#
        );
    }

    #[test]
    fn stringify_set_serializes_as_empty_object() {
        // Regression: a Set/Map header is NOT an ObjectHeader, so the old
        // catch-all object path read its internals as a `keys_array` and
        // segfaulted. Node serializes both as "{}".
        unsafe {
            let mut s = crate::set::js_set_alloc(4);
            s = crate::set::js_set_add(s, 1.0);
            s = crate::set::js_set_add(s, 2.0);
            let boxed = f64::from_bits(POINTER_TAG | (s as u64 & POINTER_MASK));
            let output = js_json_stringify(boxed, TYPE_UNKNOWN);
            assert_eq!(str_from_header(output).unwrap(), "{}");
        }
    }

    #[test]
    fn stringify_map_serializes_as_empty_object() {
        unsafe {
            let mut m = crate::map::js_map_alloc(4);
            m = crate::map::js_map_set(m, 1.0, 2.0);
            let boxed = f64::from_bits(POINTER_TAG | (m as u64 & POINTER_MASK));
            let output = js_json_stringify(boxed, TYPE_UNKNOWN);
            assert_eq!(str_from_header(output).unwrap(), "{}");
        }
    }

    #[test]
    fn stringify_buffer_pretty_indents_type_and_data() {
        // Regression (#2367): a Buffer in pretty-print mode used to reach
        // `is_object_pointer` (no buffer guard in the pretty path) and SIGSEGV.
        unsafe {
            let b = crate::buffer::js_buffer_alloc(3, 0);
            let data = (b as *mut u8).add(std::mem::size_of::<crate::buffer::BufferHeader>());
            *data = 1;
            *data.add(1) = 2;
            *data.add(2) = 3;
            let mut out = String::new();
            stringify_buffer_pretty(b as *const u8, &mut out, "  ", 0);
            assert_eq!(
                out,
                "{\n  \"type\": \"Buffer\",\n  \"data\": [\n    1,\n    2,\n    3\n  ]\n}"
            );
        }
    }

    #[test]
    fn stringify_typed_array_emits_node_index_shape() {
        // Regression (#5111): a `TypedArrayHeader`-backed typed array (small
        // ones have NO GcHeader) used to reach `gc_obj_type`, read garbage 8
        // bytes before the header, and SIGSEGV. It must serialize as the Node
        // index shape `{"0":v,…}` instead.
        unsafe {
            let ta = crate::typedarray::typed_array_alloc(crate::typedarray::KIND_INT32, 3);
            crate::typedarray::js_typed_array_set(ta, 0, 2.0);
            crate::typedarray::js_typed_array_set(ta, 1, 4.0);
            crate::typedarray::js_typed_array_set(ta, 2, 6.0);
            let boxed = f64::from_bits(POINTER_TAG | (ta as u64 & POINTER_MASK));
            let output = js_json_stringify(boxed, TYPE_UNKNOWN);
            assert_eq!(str_from_header(output).unwrap(), r#"{"0":2,"1":4,"2":6}"#);

            let mut pretty = String::new();
            stringify_typed_array_pretty(ta as *const u8, &mut pretty, "  ", 0);
            assert_eq!(pretty, "{\n  \"0\": 2,\n  \"1\": 4,\n  \"2\": 6\n}");

            let empty = crate::typedarray::typed_array_alloc(crate::typedarray::KIND_FLOAT64, 0);
            let empty_boxed = f64::from_bits(POINTER_TAG | (empty as u64 & POINTER_MASK));
            assert_eq!(
                str_from_header(js_json_stringify(empty_boxed, TYPE_UNKNOWN)).unwrap(),
                "{}"
            );
        }
    }

    #[test]
    fn direct_parse_shared_shape_roundtrips_array_records() {
        let input = br#"[{"id":1,"name":"item_1","nested":{"x":1,"y":2}},{"id":2,"name":"item_2","nested":{"x":2,"y":4}}]"#;
        let text = js_string_from_bytes(input.as_ptr(), input.len() as u32);
        let value = unsafe { js_json_parse(text) };
        let output = unsafe { js_json_stringify(f64::from_bits(value.bits()), TYPE_UNKNOWN) };

        assert_eq!(
            unsafe { str_from_header(output).unwrap() },
            std::str::from_utf8(input).unwrap()
        );
    }

    #[test]
    fn direct_parse_array_numeric_layout_preserves_and_downgrades() {
        let numeric_input = br#"[1,2,3]"#;
        let numeric_text = js_string_from_bytes(numeric_input.as_ptr(), numeric_input.len() as u32);
        let numeric_value = unsafe { js_json_parse(numeric_text) };
        let numeric_arr = (numeric_value.bits() & POINTER_MASK) as *mut crate::ArrayHeader;

        assert_eq!(crate::array::js_array_is_numeric_f64_layout(numeric_arr), 1);
        assert_eq!(
            crate::array::js_array_numeric_get_f64_unboxed(numeric_arr, 0),
            1.0
        );
        assert_eq!(
            crate::array::js_array_numeric_get_f64_unboxed(numeric_arr, 2),
            3.0
        );
        assert_eq!(
            crate::gc::test_layout_pointer_slot_count(numeric_arr as usize, 3),
            Some(0)
        );

        // Eight elements: the pointer lands while the live prefix is two, and
        // only a backing store of eight or more slots is expected to fill into
        // a mask-worthy payload; this assertion is about the pointer mask.
        let mixed_input = br#"[1,"longer",3,4,5,6,7,8]"#;
        let mixed_text = js_string_from_bytes(mixed_input.as_ptr(), mixed_input.len() as u32);
        let mixed_value = unsafe { js_json_parse(mixed_text) };
        let mixed_arr = (mixed_value.bits() & POINTER_MASK) as *mut crate::ArrayHeader;

        assert_eq!(crate::array::js_array_is_numeric_f64_layout(mixed_arr), 0);
        assert_eq!(
            crate::gc::test_layout_pointer_slot_count(mixed_arr as usize, 8),
            Some(1)
        );
    }

    #[test]
    fn stringify_non_ascii_output_keeps_utf16_len_distinct_from_bytes() {
        let input = crate::string::js_string_from_bytes("é".as_ptr(), "é".len() as u32);
        let value = f64::from_bits(crate::value::JSValue::string_ptr(input).bits());
        let output = unsafe { js_json_stringify(value, TYPE_UNKNOWN) };

        assert_eq!(unsafe { str_from_header(output).unwrap() }, "\"é\"");
        assert_eq!(unsafe { (*output).byte_len }, 4);
        assert_eq!(unsafe { (*output).utf16_len }, 3);
        assert_eq!(unsafe { (*output).flags }, 0);
    }

    #[test]
    fn stringify_wtf8_lone_surrogate_emits_unicode_escape() {
        // Issue #1182: a string containing a WTF-8 lone high surrogate
        // (U+D83D as bytes 0xED 0xA0 0xBD) must stringify to the `\ud83d`
        // escape Node's JSON.stringify produces, not the raw invalid-UTF-8
        // bytes.
        let bytes: [u8; 3] = [0xED, 0xA0, 0xBD];
        let input = crate::string::js_string_from_wtf8_bytes(bytes.as_ptr(), bytes.len() as u32);
        let value = f64::from_bits(crate::value::JSValue::string_ptr(input).bits());
        let output = unsafe { js_json_stringify(value, TYPE_UNKNOWN) };

        assert_eq!(unsafe { str_from_header(output).unwrap() }, "\"\\ud83d\"");
    }

    #[test]
    fn stringify_pairs_adjacent_wtf8_surrogates_as_astral_utf8() {
        // Issue #1182 follow-up: when a StringDecoder('utf16le') stream is
        // flushed mid-pair via .end(), the two halves end up as 6 WTF-8
        // bytes (high triple + low triple) in the concatenated result.
        // V8's JSON.stringify pairs them and emits the astral codepoint's
        // UTF-8; Perry must match. 👍 = U+1F44D = F0 9F 91 8D.
        let bytes: [u8; 6] = [0xED, 0xA0, 0xBD, 0xED, 0xB1, 0x8D];
        let input = crate::string::js_string_from_wtf8_bytes(bytes.as_ptr(), bytes.len() as u32);
        let value = f64::from_bits(crate::value::JSValue::string_ptr(input).bits());
        let output = unsafe { js_json_stringify(value, TYPE_UNKNOWN) };

        assert_eq!(unsafe { str_from_header(output).unwrap() }, "\"\u{1F44D}\"");
    }

    #[test]
    fn stringify_high_surrogate_then_bmp_still_escapes_high() {
        // Sanity: a high surrogate followed by a non-surrogate must NOT
        // be re-encoded — only valid adjacent (high, low) pairs collapse.
        // Input is 0xED A0 BD ('a' = 0x61), expected `"\ud83da"`.
        let bytes: [u8; 4] = [0xED, 0xA0, 0xBD, b'a'];
        let input = crate::string::js_string_from_wtf8_bytes(bytes.as_ptr(), bytes.len() as u32);
        let value = f64::from_bits(crate::value::JSValue::string_ptr(input).bits());
        let output = unsafe { js_json_stringify(value, TYPE_UNKNOWN) };

        assert_eq!(unsafe { str_from_header(output).unwrap() }, "\"\\ud83da\"");
    }

    #[test]
    fn stringify_3byte_utf8_below_surrogate_block_is_unchanged() {
        // U+D7FF is the codepoint immediately before the surrogate block.
        // It also starts with 0xED (0xED 0x9F 0xBF) so it exercises the
        // boundary in the WTF-8 detector — must NOT escape, must pass
        // through as raw UTF-8 bytes.
        let s = "\u{D7FF}";
        let input = crate::string::js_string_from_bytes(s.as_ptr(), s.len() as u32);
        let value = f64::from_bits(crate::value::JSValue::string_ptr(input).bits());
        let output = unsafe { js_json_stringify(value, TYPE_UNKNOWN) };

        let mut expected = String::from("\"");
        expected.push_str(s);
        expected.push('"');
        assert_eq!(unsafe { str_from_header(output).unwrap() }, expected);
    }

    #[test]
    fn stringify_empty_object_emits_braces_not_null() {
        // #1704: an object straight out of `js_object_alloc` has a null
        // `keys_array` (this is the shape of `Object.fromEntries([])`,
        // `Object.fromEntries(emptyURLSearchParams)`, and a never-mutated
        // `{}` literal). It must stringify to "{}" — pre-fix the top-level
        // path emitted the literal "null".
        let empty = crate::object::js_object_alloc(0, 0);
        assert!(unsafe { crate::object::object_keys_array(empty).is_null() });
        let boxed = crate::value::js_nanbox_pointer(empty as i64);
        let output = unsafe { js_json_stringify(boxed, TYPE_UNKNOWN) };
        assert_eq!(unsafe { str_from_header(output).unwrap() }, "{}");
    }

    #[test]
    fn stringify_nested_empty_object_does_not_segfault() {
        // #1704: a nested empty object reaches `stringify_object_inner`
        // directly via the `GC_TYPE_OBJECT` arm of `stringify_value_depth`
        // (no `is_object_pointer` guard), so the null `keys_array` read
        // would segfault. It must instead recurse to "{}" — the
        // `@hono/perry-server` handler crash was `JSON.stringify({ url, o })`
        // with `o = Object.fromEntries(emptyURLSearchParams)`.
        let empty = crate::object::js_object_alloc(0, 0);
        let outer = crate::object::js_object_alloc(0, 1);
        let key = js_string_from_bytes(b"o".as_ptr(), 1);
        let empty_boxed = crate::value::js_nanbox_pointer(empty as i64);
        crate::object::js_object_set_field_by_name(outer, key, empty_boxed);
        let outer_boxed = crate::value::js_nanbox_pointer(outer as i64);
        let output = unsafe { js_json_stringify(outer_boxed, TYPE_UNKNOWN) };
        assert_eq!(unsafe { str_from_header(output).unwrap() }, r#"{"o":{}}"#);
    }

    #[test]
    fn stringify_int32_fields_emit_integers_not_null() {
        // An int32 is NaN-boxed (INT32_TAG = 0x7FFE); its bits ARE an IEEE NaN.
        // Before the `write_number` int32 funnel, an int32 object field — e.g. a
        // sqlite INTEGER column from the better-sqlite3 binding — fell into the
        // `is_nan()` → "null" arm and serialized as `null`, silently corrupting
        // integers crossing JSON/IPC. They must emit the integer value.
        let obj = crate::object::js_object_alloc(0, 3);
        let k_id = js_string_from_bytes(b"id".as_ptr(), 2);
        let k_neg = js_string_from_bytes(b"neg".as_ptr(), 3);
        let k_zero = js_string_from_bytes(b"zero".as_ptr(), 4);
        crate::object::js_object_set_field_by_name(
            obj,
            k_id,
            f64::from_bits(JSValue::int32(42).bits()),
        );
        crate::object::js_object_set_field_by_name(
            obj,
            k_neg,
            f64::from_bits(JSValue::int32(-7).bits()),
        );
        crate::object::js_object_set_field_by_name(
            obj,
            k_zero,
            f64::from_bits(JSValue::int32(0).bits()),
        );
        let boxed = crate::value::js_nanbox_pointer(obj as i64);
        let output = unsafe { js_json_stringify(boxed, TYPE_UNKNOWN) };
        assert_eq!(
            unsafe { str_from_header(output).unwrap() },
            r#"{"id":42,"neg":-7,"zero":0}"#
        );
    }

    #[test]
    fn stringify_int32_array_elements_emit_integers_not_null() {
        // Same INT32_TAG funnel for array elements (drizzle raw-mode rows,
        // integer arrays over IPC).
        let mut arr = crate::array::js_array_alloc(3);
        arr = crate::array::js_array_push_f64(arr, f64::from_bits(JSValue::int32(1).bits()));
        arr = crate::array::js_array_push_f64(arr, f64::from_bits(JSValue::int32(2).bits()));
        arr = crate::array::js_array_push_f64(arr, f64::from_bits(JSValue::int32(-9).bits()));
        let boxed = crate::value::js_nanbox_pointer(arr as i64);
        let output = unsafe { js_json_stringify(boxed, TYPE_ARRAY) };
        assert_eq!(unsafe { str_from_header(output).unwrap() }, "[1,2,-9]");
    }

    #[test]
    fn stringify_uses_two_char_short_forms_for_backspace_and_formfeed() {
        // #5047: QuoteJSONString mandates the two-character escapes for
        // U+0008 (\b) and U+000C (\f); Perry emitted the 4-hex-digit form for both. Other
        // control characters keep the 4-hex-digit form.
        let input = b"a\x08b\x0cc\x0bd";
        let s = js_string_from_bytes(input.as_ptr(), input.len() as u32);
        let boxed = f64::from_bits(STRING_TAG | (s as u64 & POINTER_MASK));
        let output = unsafe { js_json_stringify(boxed, TYPE_UNKNOWN) };
        assert_eq!(
            unsafe { str_from_header(output).unwrap() },
            "\"a\\bb\\fc\\u000bd\""
        );
    }

    /// Materialize `src` exactly the way `JSON.parse` does once a property
    /// read forces the lazy tape to become real objects, and return both the
    /// value and the resulting `(field_count, keys_len)` of element 0.
    unsafe fn materialized_array(src: &[u8]) -> (JSValue, u32, u32) {
        let tape = crate::json_tape::build_tape(src).expect("tape builds for valid JSON");
        let value = crate::json_tape::materialize(&tape, src);
        let arr = (value.bits() & POINTER_MASK) as *mut crate::ArrayHeader;
        let elem0 = crate::array::js_array_get(arr, 0);
        let obj = (elem0.bits() & POINTER_MASK) as *const crate::ObjectHeader;
        (
            value,
            crate::object::object_live_slot_count(obj),
            (*crate::object::object_keys_array(obj)).length,
        )
    }

    #[test]
    fn stringify_array_keeps_every_property_of_name_grown_elements() {
        // #7264: `JSON.stringify` silently dropped every property past the
        // 4th from EVERY element of a homogeneous array.
        //
        // The array fast path built its shape template with
        // `min(keys_len, field_count)`. `field_count` is PHYSICAL — it never
        // exceeds the object's inline slot allocation, so an object grown by
        // name past `INLINE_SLOT_FLOOR` reports the floor while the
        // remaining values live in overflow storage. `JSON.parse`'s tape
        // materializer produces exactly that shape (`js_object_alloc(0, 0)` +
        // `js_object_set_field_by_name` per key), so `JSON.stringify` of a
        // parsed-and-touched array truncated every record to 4 fields.
        //
        // Latent since the shape template landed (v0.5.65, 9-field threshold);
        // exposed for ordinary 5–8-field records by #6712 (floor 8 → 4).
        let src = br#"[{"f0":0,"f1":1,"f2":2,"f3":3,"f4":4,"f5":5},{"f0":10,"f1":11,"f2":12,"f3":13,"f4":14,"f5":15}]"#;
        unsafe {
            let (value, field_count, keys_len) = materialized_array(src);
            // Assert the gate's SUBJECT is live: this test is only meaningful
            // while the materializer really does leave `field_count` below
            // `keys_len` (the overflow shape). If a future change pre-sizes
            // the allocation, this assertion fires and the test must be
            // re-pointed rather than silently passing on the easy path.
            assert!(
                field_count < keys_len,
                "precondition lost: tape-materialized element is no longer an \
                 overflow shape (field_count={field_count}, keys_len={keys_len}) — \
                 re-point this regression test at a shape that still is"
            );
            assert_eq!(keys_len, 6);

            let output = js_json_stringify(f64::from_bits(value.bits()), TYPE_ARRAY);
            assert_eq!(
                str_from_header(output).unwrap(),
                std::str::from_utf8(src).unwrap(),
                "array-element serialization must emit all {keys_len} properties"
            );
        }
    }

    #[test]
    fn stringify_array_round_trips_every_field_count_across_the_inline_floor() {
        // The truncation was invisible at ≤ INLINE_SLOT_FLOOR fields and
        // produced IDENTICAL output for 5, 6 and 8 — the tell that emission
        // stopped at the floor. Sweep across the boundary.
        for n in 1..=10usize {
            let record = |base: usize| {
                let fields: Vec<String> =
                    (0..n).map(|f| format!("\"f{f}\":{}", base + f)).collect();
                format!("{{{}}}", fields.join(","))
            };
            let src = format!("[{},{}]", record(0), record(100));
            unsafe {
                let tape = crate::json_tape::build_tape(src.as_bytes()).expect("tape");
                let value = crate::json_tape::materialize(&tape, src.as_bytes());
                let output = js_json_stringify(f64::from_bits(value.bits()), TYPE_ARRAY);
                assert_eq!(
                    str_from_header(output).unwrap(),
                    src.as_str(),
                    "{n}-field records must round-trip"
                );
            }
        }
    }

    #[test]
    fn stringify_array_keeps_nested_objects_and_arrays_past_the_inline_floor() {
        // The shape reported in #7264: the 5th property is a nested object and
        // the 4th an array, so the dropped field was a whole subtree.
        let src = br#"[{"id":0,"name":"item_0","value":0,"tags":["tag_0","tag_0"],"nested":{"x":0,"y":0}},{"id":1,"name":"item_1","value":3,"tags":["tag_1","tag_1"],"nested":{"x":1,"y":2}}]"#;
        unsafe {
            let (value, field_count, keys_len) = materialized_array(src);
            assert!(field_count < keys_len, "precondition: overflow shape");
            let output = js_json_stringify(f64::from_bits(value.bits()), TYPE_ARRAY);
            assert_eq!(
                str_from_header(output).unwrap(),
                std::str::from_utf8(src).unwrap()
            );
        }
    }

    #[test]
    fn stringify_array_omits_a_function_valued_property_of_a_later_element() {
        // Second defect found in the same emitter while fixing #7264. The
        // template's primitive-only fast path is chosen by SAMPLING element 0;
        // it then trusted every later element to be primitive too. A function
        // (or symbol) value in a later element must be OMITTED per
        // SerializeJSONObject, but the fast path had already written the key
        // prefix and rendered the closure as `null` — emitting a member that
        // must not exist. Only the general (non-primitive-only) path pre-scanned
        // for it. Applies to inline slots as much as overflow ones.
        let src = br#"[{"f0":0,"f1":1,"f2":2,"f3":3,"f4":4,"f5":5},{"f0":10,"f1":11,"f2":12,"f3":13,"f4":14,"f5":15}]"#;
        unsafe {
            let (value, _, _) = materialized_array(src);
            let arr = (value.bits() & POINTER_MASK) as *mut crate::ArrayHeader;
            let elem1 = crate::array::js_array_get(arr, 1);
            let obj1 = (elem1.bits() & POINTER_MASK) as *mut crate::ObjectHeader;
            // `f4` is at index 4 — an OVERFLOW slot on this shape, so this also
            // covers the fallback plumbing added for overflow reads.
            let closure = crate::closure::js_closure_alloc(std::ptr::null(), 0);
            let key = js_string_from_bytes(b"f4".as_ptr(), 2);
            crate::object::js_object_set_field_by_name(
                obj1,
                key,
                f64::from_bits(POINTER_TAG | (closure as u64 & POINTER_MASK)),
            );

            let output = js_json_stringify(f64::from_bits(value.bits()), TYPE_ARRAY);
            assert_eq!(
                str_from_header(output).unwrap(),
                r#"[{"f0":0,"f1":1,"f2":2,"f3":3,"f4":4,"f5":5},{"f0":10,"f1":11,"f2":12,"f3":13,"f5":15}]"#
            );
        }
    }

    #[test]
    fn stringify_array_stops_at_the_last_real_key_when_slots_were_pre_sized() {
        // The opposite skew, and the reason the truncating `min` existed: an
        // object allocated with MORE inline slots than it has keys
        // (`js_object_alloc(0, 8)` holding 2 properties). `keys_len` alone must
        // still stop at the last real key rather than dumping padding slots.
        unsafe {
            let mut arr = crate::array::js_array_alloc(2);
            for base in [1.0f64, 10.0f64] {
                let obj = crate::object::js_object_alloc(0, 8);
                for (i, name) in ["a", "b"].iter().enumerate() {
                    let key = js_string_from_bytes(name.as_ptr(), name.len() as u32);
                    crate::object::js_object_set_field_by_name(obj, key, base + i as f64);
                }
                assert!(
                    crate::object::object_live_slot_count(obj)
                        >= (*crate::object::object_keys_array(obj)).length
                );
                arr = crate::array::js_array_push(arr, JSValue::object_ptr(obj as *mut u8));
            }
            let boxed = crate::value::js_nanbox_pointer(arr as i64);
            let output = js_json_stringify(boxed, TYPE_ARRAY);
            assert_eq!(
                str_from_header(output).unwrap(),
                r#"[{"a":1,"b":2},{"a":10,"b":11}]"#
            );
        }
    }

    /// #7477: the DirectParser must produce bit-identical f64s to the tape
    /// materializer, whose number path is `str::parse::<f64>()` (correctly
    /// rounded, matches V8's strtod for round-trippable inputs). The
    /// DirectParser's small fixed-point fast path computed
    /// `int as f64 + (frac as f64 / 10^k)` — TWO IEEE roundings (the division
    /// rounds, then the addition rounds again), which is off by one ulp for
    /// some literals. Node agrees with the tape, so the DirectParser is the
    /// wrong one.
    ///
    /// `260.75197` (= 83 * 3.14159 in f64) is the minimal diverging literal
    /// from `bench_field_access`: correct bits 0x1.04c0811b1d92bp+8, the
    /// double-rounded fast path returned 0x1.04c0811b1d92cp+8 — whose
    /// shortest round-trip stringification is "260.75197000000004", which is
    /// how a pure parse divergence surfaced as a stringify-length checksum
    /// mismatch (2552986400 vs node's 2552985550).
    #[test]
    fn direct_parser_number_bits_match_strtod() {
        let parse_direct = |s: &str| -> u64 {
            let bytes = s.as_bytes();
            let mut parser = DirectParser::new(bytes);
            let value = unsafe { parser.parse_number() };
            assert!(
                !parser.has_trailing_content(),
                "parse_number left trailing input on {s:?}"
            );
            value.bits()
        };
        let mut cases: Vec<String> = vec![
            // The two bench_field_access literals that diverged (#7477),
            // plus their negations.
            "260.75197".to_string(),
            "521.50394".to_string(),
            "-260.75197".to_string(),
            "-521.50394".to_string(),
            // Assorted shapes through every parse_number arm: integer fast
            // path, fixed-point fast path, exponent / long-token fallback.
            "0".to_string(),
            "-0".to_string(),
            "0.1".to_string(),
            "-0.1".to_string(),
            "0.3".to_string(),
            "3.14159".to_string(),
            "1.0000001".to_string(),
            "123.456".to_string(),
            "999999999999999.9".to_string(),
            "9007199254740993.1".to_string(),
            "0.000000001".to_string(),
            "12345678901234567890".to_string(),
            "1e10".to_string(),
            "-2.5e-3".to_string(),
            "1.7976931348623157e308".to_string(),
        ];
        // The full bench_field_access value space: shortest round-trip
        // renderings of i * 3.14159. Two of these (i = 83, 166) diverged
        // under the double-rounding fast path.
        for i in 0..10000 {
            cases.push(format!("{}", i as f64 * 3.14159));
        }
        for s in &cases {
            let want: f64 = s.parse().unwrap();
            let got = parse_direct(s);
            assert_eq!(
                got,
                want.to_bits(),
                "DirectParser::parse_number({s:?}) = {:#018x} ({}), \
                 str::parse (tape/node) = {:#018x} ({})",
                got,
                f64::from_bits(got),
                want.to_bits(),
                want,
            );
        }
    }
}
